feat: Add optional Tests/TCK builds.
hiero-ledger/hiero-sdk-cpp pull request #824
Opened 2024-11-13 12:26 UTC by gsstoykov

**Description**:
Introduces flags for optional builds:
* BUILD_TCK - building the TCK project
* BUILD_TESTS - building the unit/integration test suites

**Related issue(s)**:

Fixes https://github.com/hiero-ledger/hiero-sdk-cpp/issues/816

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-11-13 15:20 UTC, rwalworth requested changes

2024-11-13 15:20 UTC, rwalworth commented on README.md
> +
Should add a flag for building the examples as well

2024-11-13 18:09 UTC, andrewb1269hg submitted a review, later dismissed

2024-11-14 15:08 UTC, rwalworth approved these changes
LGTM

2024-11-14 17:29 UTC, merged