ci: Test Windows builds
hiero-ledger/hiero-sdk-cpp pull request #865
Opened 2024-12-18 08:52 UTC by mishomihov00

Test Windows builds

2025-01-03 20:41 UTC, rwalworth submitted a review, later dismissed
LGTM

2025-01-06 16:22 UTC, rwalworth approved these changes

2025-01-06 16:37 UTC, rbarkerSL requested changes

2025-01-06 16:37 UTC, rbarkerSL commented on .github/workflows/zxc-build-library.yaml
> +    if: ${{ (inputs.run-macos-builds) && !cancelled() }}
add an if check for github.event_name == 'workflow_dispatch' on here so that it doesn't error out the workflow on a workflow_call trigger.

2025-01-07 08:32 UTC, mishomihov00 commented on .github/workflows/zxc-build-library.yaml
> +          useCloudCache: false #Seems to be failing due to a timeout.
It seems to be working now.

2025-01-08 08:21 UTC, rbarkerSL approved these changes

2025-01-08 13:51 UTC, merged